import { Injectable } from '@angular/core';

const TRANSLATIONS = {
    // Setup
    subtitle: 'Football trivia for 2 players',
    generatingQuestions: 'Generating Questions...',
    generatingSubtitle: 'Fetching live football data & crafting your quiz',
    enterNames: 'Enter Player Names',
    player1Placeholder: 'Player 1 name...',
    player2Placeholder: 'Player 2 name...',
    kickOff: 'Kick Off! ⚽',
    howToPlay: '7 categories · Up to 3 difficulties · 2 lifelines each',
    failedToStart: 'Failed to start game. Please try again.',
    // Board
    turn: 'Turn',
    end: 'End',
    cancel: 'Cancel',
    endGameConfirm: 'End the game?',
    use2x: 'USE 2x',
    armed2x: '2x ARMED',
    streak: 'Streak',
    accuracy: 'Accuracy',
    // Question
    yourTurn: "'s turn",
    typeAnswer: 'Type your answer...',
    submit: 'Submit',
    higher: '▲ Higher',
    lower: '▼ Lower',
    clubName: 'Club name...',
    playerName: 'Player name...',
    scorePlaceholder: 'Score e.g. 2-1',
    guess: 'Guess',
    typePlayer: 'Type a player name...',
    use5050: '🎯 Use 50-50 (reduces to 1 pt)',
    fiftyPick: '🎯 50-50 — Pick one (1 pt if correct)',
    doubleArmed: '2x ARMED — double points if correct!',
    found: '/5 found',
    lives: 'Lives:',
    notInTop5Label: 'Not in top 5',
    notInTop5: '✗ not in top 5',
    stopEarly: 'Stop now — take 1pt (missing 1 answer)',
    allFound: '🏆 All 5 found! Full points!',
    stoppedEarly: '✅ Stopped at 4/5 — 1pt awarded',
    questionLost: '💀 Question lost — too many wrong guesses',
    oneWrong: '⚠️ 1 wrong guess — one more and the question is lost!',
    answersInEnglish: '',
    loanSpell: 'Loan',
    home: 'Home',
    away: 'Away',
    backToHome: '← Back',
    // Category labels
    catHistory: 'HISTORY',
    catPlayerId: 'PLAYER ID',
    catLogoQuiz: 'LOGO QUIZ',
    catHigherLower: 'HIGHER / LOWER',
    catGuessScore: 'GUESS THE SCORE',
    catGeography: 'GEOGRAPHY',
    catGossip: 'GOSSIP',
    catTop5: 'TOP 5',
    catNews: 'NEWS',
    // Category labels (question view)
    catHistoryQ: 'History',
    catPlayerIdQ: 'Player ID',
    catLogoQuizQ: 'Logo Quiz',
    catHigherLowerQ: 'Higher or Lower',
    catGuessScoreQ: 'Guess the Score',
    catGeographyQ: 'Geography',
    catGossipQ: 'Gossip',
    catTop5Q: 'Top 5',
    catNewsQ: 'News',
    // Result
    correct: 'Correct!',
    wrong: 'Wrong!',
    noPoints: 'No points awarded',
    correctAnswer: 'Correct Answer',
    reportProblem: 'Report a problem',
    reportCooldown: 'Report sent (1 min cooldown)',
    problemReported: 'Problem reported',
    markCorrect: '✓ Mark Correct',
    markWrong: '✗ Mark Wrong',
    seeFinal: 'See Final Results →',
    backToBoard: 'Back to Board →',
    // Results
    finalResults: 'Final Results',
    gameComplete: 'Unlimited Quizball Complete!',
    itsDraw: "🤝 It's a Draw!",
    wins: 'wins!',
    points: 'points',
    lifelineUsed: 'Lifeline: Used',
    lifelineNotUsed: 'Lifeline: Not used',
    doubleUsed: '2x: Used',
    doubleNotUsed: '2x: Not used',
    categoryBreakdown: 'Category Breakdown',
    playAgain: 'Play Again ⚽',
    // Home
    appTitle: 'Unlimited Quizball',
    appTitlePart1: 'Unlimited',
    appTitlePart2: 'Quizball',
    appSubtitle: 'The football trivia game',
    signOut: 'Sign out',
    settingsTitle: 'Settings',
    settingsAppearance: 'Appearance',
    settingsDarkMode: 'Dark mode',
    settingsLanguage: 'Language',
    btn2Player: '2-Player Game',
    btn2PlayerResume: 'Resume 2-Player',
    btnSolo: 'Solo Ranked',
    btnBlitz: 'Blitz Mode',
    btnDaily: 'Today in Football',
    loginRequired: 'Login required',
    soloStatsHint: 'ELO',
    blitzStatsHint: 'Best',
    rankLabel: 'Rank',
    btn2PlayerHint: '2 players · 8 categories · 1 lifeline each',
    btnSoloDesc: 'ELO ranked · adaptive difficulty',
    btnBlitzDesc: '60 seconds · multiple choice',
    dailyResetsIn: 'Resets in',
    dailyQuestionsLabel: 'questions',
    gameModes: 'Game Modes',
    compete: 'Compete',
    proArena: 'Pro Arena',
    viewAll: 'View All',
    startMatch: 'Start Match',
    localMultiplayer: 'Local Multiplayer',
    eloSystem: 'ELO SYSTEM',
    playersOnline: '12K Players Online',
    speedrun: 'SPEEDRUN',
    dailyPlay: 'Play',
    dailyChallenge: 'Daily Challenge',
    // Nav
    navHome: 'Home',
    navInvite: 'Invite',
    navLeaderboard: 'Leaderboard',
    navRank: 'Rank',
    navProfile: 'Profile',
    // Daily
    dailyTitle: 'Today in Football',
    dailySubtitle: 'On this day in football history.',
    dailySameQuestions: 'Same questions for everyone today. How many can you get right?',
    dailyStart: 'Start Quiz',
    dailyLoading: 'Loading...',
    dailyAllDone: 'All Done!',
    dailyQuestionOf: 'Question',
    dailyCorrectPct: 'correct',
    dailyNoQuestions: 'No questions available for today. Try again later.',
    dailyLoadFailed: 'Failed to load questions',
    dailyBackBtn: '← Home',
    tapToContinue: 'Tap to continue',
    // Blitz
    blitzTitle: 'Blitz Mode',
    blitzSubtitle: '60 seconds. Answer as many as you can.',
    blitzBullet1: 'Pick from 3 choices — no typing required',
    blitzBullet2: 'Fast-paced: each question appears right after you answer',
    blitzBullet3: 'Your best score is saved and ranked on the leaderboard',
    blitzBullet4: 'Perfect for quick sessions and testing your knowledge',
    blitzStart: 'Start Blitz',
    blitzAnswered: 'answered',
    blitzTimesUp: "Time's Up!",
    blitzCorrectOutOf: 'correct out of',
    blitzBackBtn: '← Home',
    // Solo
    soloTitle: 'Solo Ranked',
    soloSubtitle: 'Answer football questions to earn ELO and climb the leaderboard.',
    soloBullet1: 'Type your answers — no multiple choice',
    soloBullet2: 'Adaptive difficulty: EASY (10s), MEDIUM (15s), HARD (20s)',
    soloBullet3: 'Win ELO on correct answers, lose on wrong or timeout',
    soloBullet4: 'Play as many questions as you like per session',
    soloStartingElo: 'Starting ELO:',
    soloStarting: 'Starting...',
    soloStartPlaying: 'Start Playing',
    soloYourAnswer: 'Your answer...',
    soloTimesUp: "Time's up!",
    soloAnswerLabel: 'Answer:',
    soloEloChange: 'ELO Change',
    soloNewElo: 'New ELO',
    soloNextQuestion: 'Next Question',
    soloEnd: 'End',
    soloSessionComplete: 'Session Complete',
    soloStartingEloLabel: 'Starting ELO',
    soloFinalElo: 'Final ELO',
    soloViewLeaderboard: 'View Leaderboard',
    soloPlayAgain: 'Play Again',
    soloOk: 'OK',
    soloBackBtn: '← Home',
    soloCorrect: 'Correct!',
    soloWrong: 'Wrong',
    soloCorrectCount: 'Correct',
    soloEasy: 'EASY',
    soloMedium: 'MEDIUM',
    soloHard: 'HARD',
    // Leaderboard
    lbTitle: 'Leaderboard',
    lbRefresh: 'Refresh',
    lbLoading: 'Loading...',
    lbSolo: 'Solo Ranked',
    lbBlitz: 'Blitz Mode',
    lbYou: '(you)',
    lbNoPlayers: 'No players yet. Be the first!',
    lbNoBlitz: 'No Blitz scores yet. Play now!',
    lbYourRank: 'Your rank',
    lbQuestions: 'questions',
    lbAnswered: 'answered',
    lbBest: 'Best',
    lbAccuracy: 'accuracy',
    lbLoadFailed: 'Failed to load leaderboard',
    blitzSessionFailed: 'Failed to start session',
    // Invite
    inviteTitle: 'Invite a Friend',
    inviteSubtitle: 'Share the link so they can try football trivia.',
    inviteCopy: 'Copy link',
    inviteCopied: 'Copied!',
    inviteShare: 'Share via...',
    inviteHowItWorks: 'How it works',
    inviteStep1: 'Share the link with a friend',
    inviteStep2: 'They open it and try the app',
    inviteStep3: 'Play 2-player head-to-head on the same device',
    // Profile
    profileTitle: 'Your Profile',
    profileGuestText: 'Sign in to track your ELO, Blitz scores, and compete on the leaderboard.',
    profileSignIn: 'Sign in',
    profileLoading: 'Loading profile...',
    profileElo: 'ELO',
    profileMaxElo: 'Max ELO',
    profileBlitzBest: 'Blitz Best',
    profileGames: 'Games',
    profileAccuracy: 'Accuracy',
    profilePeakRating: 'Peak rating',
    profileSoloPlayed: 'Solo played',
    profileSoloQuestions: 'Solo questions',
    profileViewLeaderboard: 'View Leaderboard',
    profileBackToLeaderboard: 'Back to Leaderboard',
    matchHistory: 'Match History',
    achievements: 'Achievements',
    // Donate modal
    donateModalTitle: 'Enjoying the game?',
    donateModalMessage: 'If you\'re having fun, consider supporting the creator with a coffee. Every bit helps!',
    donateModalSupport: 'Support on Ko-fi',
    donateModalMaybeLater: 'Maybe later',
    navBuyMeACoffee: 'Buy me a coffee',
    // News mode
    btnNews: 'NEWS',
    btnNewsHint: 'Latest football headlines • Hourly updates',
    newsDailyBadge: 'HOURLY',
    newsLatestHeadlines: 'Latest headlines',
    // Mayhem mode
    btnMayhem: 'MAYHEM',
    btnMayhemHint: 'Extremely hard trivia • All around the world',
    mayhemNewBadge: 'EXTREME',
    mayhemSubtitle: 'Obscure world football trivia',
    mayhemFinishedTitle: 'Mayhem Complete!',
    mayhemFinishedSubtitle: 'You survived the hardest football trivia.',
} as const;

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly t = () => TRANSLATIONS;
}
