import { Injectable, signal, computed } from '@angular/core';

export type Language = 'en' | 'el';

const TRANSLATIONS = {
  en: {
    // Setup
    subtitle: 'Football trivia for 2 players',
    generatingQuestions: 'Generating Questions...',
    generatingSubtitle: 'Fetching live football data & crafting your quiz',
    enterNames: 'Enter Player Names',
    player1Placeholder: 'Player 1 name...',
    player2Placeholder: 'Player 2 name...',
    kickOff: 'Kick Off! ⚽',
    howToPlay: '8 categories · Up to 3 difficulties · 1 lifeline each',
    failedToStart: 'Failed to start game. Please try again.',
    // Board
    turn: 'Turn',
    end: 'End',
    cancel: 'Cancel',
    endGameConfirm: 'End the game?',
    use2x: 'USE 2x',
    armed2x: '2x ARMED',
    streak: 'Streak',
    accuracy: 'Accuracy',
    // Question
    yourTurn: "'s turn",
    typeAnswer: 'Type your answer...',
    submit: 'Submit',
    higher: '▲ Higher',
    lower: '▼ Lower',
    clubName: 'Club name...',
    playerName: 'Player name...',
    scorePlaceholder: 'Score e.g. 2-1',
    guess: 'Guess',
    typePlayer: 'Type a player name...',
    use5050: '🎯 Use 50-50 (reduces to 1 pt)',
    fiftyPick: '🎯 50-50 — Pick one (1 pt if correct)',
    doubleArmed: '2x ARMED — double points if correct!',
    found: '/5 found',
    lives: 'Lives:',
    notInTop5Label: 'Not in top 5',
    notInTop5: '✗ not in top 5',
    stopEarly: 'Stop now — take 1pt (missing 1 answer)',
    allFound: '🏆 All 5 found! Full points!',
    stoppedEarly: '✅ Stopped at 4/5 — 1pt awarded',
    questionLost: '💀 Question lost — too many wrong guesses',
    oneWrong: '⚠️ 1 wrong guess — one more and the question is lost!',
    answersInEnglish: '',
    home: 'Home',
    away: 'Away',
    backToHome: '← Back',
    // Category labels
    catHistory: 'HISTORY',
    catPlayerId: 'PLAYER ID',
    catLogoQuiz: 'LOGO QUIZ',
    catHigherLower: 'HIGHER / LOWER',
    catGuessScore: 'GUESS THE SCORE',
    catGeography: 'GEOGRAPHY',
    catGossip: 'GOSSIP',
    catTop5: 'TOP 5',
    catNews: 'NEWS',
    // Category labels (question view)
    catHistoryQ: 'History',
    catPlayerIdQ: 'Player ID',
    catLogoQuizQ: 'Logo Quiz',
    catHigherLowerQ: 'Higher or Lower',
    catGuessScoreQ: 'Guess the Score',
    catGeographyQ: 'Geography',
    catGossipQ: 'Gossip',
    catTop5Q: 'Top 5',
    catNewsQ: 'News',
    // Result
    correct: 'Correct!',
    wrong: 'Wrong!',
    noPoints: 'No points awarded',
    correctAnswer: 'Correct Answer',
    reportProblem: 'Report a problem',
    reportCooldown: 'Report sent (1 min cooldown)',
    problemReported: 'Problem reported',
    markCorrect: '✓ Mark Correct',
    markWrong: '✗ Mark Wrong',
    seeFinal: 'See Final Results →',
    backToBoard: 'Back to Board →',
    // Results
    finalResults: 'Final Results',
    gameComplete: 'Unlimited Quizball Complete!',
    itsDraw: "🤝 It's a Draw!",
    wins: 'wins!',
    points: 'points',
    lifelineUsed: 'Lifeline: Used',
    lifelineNotUsed: 'Lifeline: Not used',
    doubleUsed: '2x: Used',
    doubleNotUsed: '2x: Not used',
    categoryBreakdown: 'Category Breakdown',
    playAgain: 'Play Again ⚽',
    // Home
    appTitle: 'Unlimited Quizball',
    appTitlePart1: 'Unlimited',
    appTitlePart2: 'Quizball',
    appSubtitle: 'The football trivia game',
    signOut: 'Sign out',
    btn2Player: '2-Player Game',
    btn2PlayerResume: 'Resume 2-Player',
    btnSolo: 'Solo Ranked',
    btnBlitz: 'Blitz Mode',
    btnDaily: 'Today in Football',
    loginRequired: 'Login required',
    soloStatsHint: 'ELO',
    blitzStatsHint: 'Best',
    rankLabel: 'Rank',
    btn2PlayerHint: '2 players · 8 categories · 1 lifeline each',
    btnSoloDesc: 'ELO ranked · adaptive difficulty',
    btnBlitzDesc: '60 seconds · multiple choice',
    dailyResetsIn: 'Resets in',
    dailyQuestionsLabel: 'questions',
    gameModes: 'Game Modes',
    viewAll: 'View All',
    startMatch: 'Start Match',
    localMultiplayer: 'Local Multiplayer',
    eloSystem: 'ELO SYSTEM',
    playersOnline: '12K Players Online',
    speedrun: 'SPEEDRUN',
    dailyPlay: 'Play',
    dailyChallenge: 'Daily Challenge',
    // Nav
    navHome: 'Home',
    navInvite: 'Invite',
    navLeaderboard: 'Leaderboard',
    navRank: 'Rank',
    navProfile: 'Profile',
    // Daily
    dailyTitle: 'Today in Football',
    dailySubtitle: 'On this day in football history.',
    dailySameQuestions: 'Same questions for everyone today. How many can you get right?',
    dailyStart: 'Start Quiz',
    dailyLoading: 'Loading...',
    dailyAllDone: 'All Done!',
    dailyQuestionOf: 'Question',
    dailyCorrectPct: 'correct',
    dailyNoQuestions: 'No questions available for today. Try again later.',
    dailyLoadFailed: 'Failed to load questions',
    dailyBackBtn: '← Home',
    tapToContinue: 'Tap to continue',
    // Blitz
    blitzTitle: 'Blitz Mode',
    blitzSubtitle: '60 seconds. Answer as many as you can.',
    blitzBullet1: 'Pick from 3 choices — no typing required',
    blitzBullet2: 'Fast-paced: each question appears right after you answer',
    blitzBullet3: 'Your best score is saved and ranked on the leaderboard',
    blitzBullet4: 'Perfect for quick sessions and testing your knowledge',
    blitzStart: 'Start Blitz',
    blitzAnswered: 'answered',
    blitzTimesUp: "Time's Up!",
    blitzCorrectOutOf: 'correct out of',
    blitzBackBtn: '← Home',
    // Leaderboard
    lbTitle: 'Leaderboard',
    lbRefresh: 'Refresh',
    lbLoading: 'Loading...',
    lbSolo: 'Solo Ranked',
    lbBlitz: 'Blitz Mode',
    lbYou: '(you)',
    lbNoPlayers: 'No players yet. Be the first!',
    lbNoBlitz: 'No Blitz scores yet. Play now!',
    lbYourRank: 'Your rank',
    lbQuestions: 'questions',
    lbAnswered: 'answered',
    lbBest: 'Best',
    lbAccuracy: 'accuracy',
    lbLoadFailed: 'Failed to load leaderboard',
    blitzSessionFailed: 'Failed to start session',
    // Invite
    inviteTitle: 'Invite a Friend',
    inviteSubtitle: 'Share the link so they can try football trivia.',
    inviteCopy: 'Copy link',
    inviteCopied: 'Copied!',
    inviteShare: 'Share via...',
    inviteHowItWorks: 'How it works',
    inviteStep1: 'Share the link with a friend',
    inviteStep2: 'They open it and try the app',
    inviteStep3: 'Play 2-player head-to-head on the same device',
    // Profile
    profileTitle: 'Your Profile',
    profileGuestText: 'Sign in to track your ELO, Blitz scores, and compete on the leaderboard.',
    profileSignIn: 'Sign in',
    profileLoading: 'Loading profile...',
    profileElo: 'ELO',
    profileMaxElo: 'Max ELO',
    profileBlitzBest: 'Blitz Best',
    profileGames: 'Games',
    profileAccuracy: 'Accuracy',
    profilePeakRating: 'Peak rating',
    profileSoloPlayed: 'Solo played',
    profileSoloQuestions: 'Solo questions',
    profileViewLeaderboard: 'View Leaderboard',
    profileBackToLeaderboard: 'Back to Leaderboard',
    // Donate modal
    donateModalTitle: 'Enjoying the game?',
    donateModalMessage: 'If you\'re having fun, consider supporting the creator with a coffee. Every bit helps!',
    donateModalSupport: 'Support on Ko-fi',
    donateModalMaybeLater: 'Maybe later',
    navBuyMeACoffee: 'Buy me a coffee',
  },
  el: {
    // Setup
    subtitle: 'Ποδοσφαιρικό κουίζ για 2 παίκτες',
    generatingQuestions: 'Δημιουργία Ερωτήσεων...',
    generatingSubtitle: 'Φόρτωση δεδομένων & δημιουργία κουίζ',
    enterNames: 'Εισάγετε Ονόματα Παικτών',
    player1Placeholder: 'Όνομα Παίκτη 1...',
    player2Placeholder: 'Όνομα Παίκτη 2...',
    kickOff: 'Έναρξη! ⚽',
    howToPlay: '8 κατηγορίες · Μέχρι 3 επίπεδα δυσκολίας · 1 βοήθεια ο καθένας',
    failedToStart: 'Αποτυχία εκκίνησης. Παρακαλώ δοκιμάστε ξανά.',
    // Board
    turn: 'Σειρά',
    end: 'Τέλος',
    cancel: 'Ακύρωση',
    endGameConfirm: 'Τερματισμός παιχνιδιού;',
    use2x: '2x',
    armed2x: '2x ΕΤΟΙΜΟ',
    streak: 'Σειρά',
    accuracy: 'Ακρίβεια',
    // Question
    yourTurn: " η σειρά",
    typeAnswer: 'Πληκτρολογήστε απάντηση...',
    submit: 'Υποβολή',
    higher: '▲ Ψηλότερα',
    lower: '▼ Χαμηλότερα',
    clubName: 'Όνομα ομάδας...',
    playerName: 'Όνομα παίκτη...',
    scorePlaceholder: 'Σκορ π.χ. 2-1',
    guess: 'Εικασία',
    typePlayer: 'Πληκτρολογήστε παίκτη...',
    use5050: '🎯 Χρήση 50-50 (μειώνει σε 1 βαθμό)',
    fiftyPick: '🎯 50-50 — Επέλεξε (1 βαθμός αν σωστό)',
    doubleArmed: '2x ΕΤΟΙΜΟ — διπλοί βαθμοί αν σωστό!',
    found: '/5 βρέθηκαν',
    lives: 'Ζωές:',
    notInTop5Label: 'Εκτός top 5',
    notInTop5: '✗ εκτός top 5',
    stopEarly: 'Σταμάτα — πάρε 1 βαθμό (λείπει 1)',
    allFound: '🏆 5/5 βρέθηκαν! Πλήρεις βαθμοί!',
    stoppedEarly: '✅ Σταμάτησες στο 4/5 — 1 βαθμός',
    questionLost: '💀 Χάθηκε η ερώτηση — πολλά λάθη',
    oneWrong: '⚠️ 1 λάθος — άλλο ένα και χάνεις!',
    answersInEnglish: '* Οι απαντήσεις πρέπει να είναι στα Αγγλικά',
    home: 'Γηπεδούχος',
    away: 'Φιλοξενούμενος',
    backToHome: '← Πίσω',
    // Category labels (board)
    catHistory: 'ΙΣΤΟΡΙΑ',
    catPlayerId: 'ΠΑΙΚΤΗΣ',
    catLogoQuiz: 'ΛΟΓΟΤΥΠΑ',
    catHigherLower: 'ΨΗΛΟ / ΧΑΜΗΛΟ',
    catGuessScore: 'ΜΑΝΤΕΨΕ ΤΟ ΣΚΟΡ',
    catGeography: 'ΓΕΩΓΡΑΦΙΑ',
    catGossip: 'GOSSIP',
    catTop5: 'TOP 5',
    catNews: 'ΝΕΑ',
    // Category labels (question view)
    catHistoryQ: 'Ιστορία',
    catPlayerIdQ: 'Παίκτης',
    catLogoQuizQ: 'Λογότυπα',
    catHigherLowerQ: 'Ψηλό ή Χαμηλό',
    catGuessScoreQ: 'Μάντεψε το Σκορ',
    catGeographyQ: 'Γεωγραφία',
    catGossipQ: 'Gossip',
    catTop5Q: 'Top 5',
    catNewsQ: 'Νέα',
    // Result
    correct: 'Σωστό!',
    wrong: 'Λάθος!',
    noPoints: 'Κανένας βαθμός',
    correctAnswer: 'Σωστή Απάντηση',
    reportProblem: 'Αναφορά προβλήματος',
    reportCooldown: 'Απεστάλη (1 λεπτό αναμονή)',
    problemReported: 'Το πρόβλημα αναφέρθηκε',
    markCorrect: '✓ Σωστό',
    markWrong: '✗ Λάθος',
    seeFinal: 'Τελικά Αποτελέσματα →',
    backToBoard: 'Πίσω στο Ταμπλό →',
    // Results
    finalResults: 'Τελικά Αποτελέσματα',
    gameComplete: 'Ολοκλήρωση Unlimited Quizball!',
    itsDraw: '🤝 Ισοπαλία!',
    wins: 'κερδίζει!',
    points: 'βαθμοί',
    lifelineUsed: 'Βοήθεια: Χρησιμοποιήθηκε',
    lifelineNotUsed: 'Βοήθεια: Δεν χρησιμοποιήθηκε',
    doubleUsed: '2x: Χρησιμοποιήθηκε',
    doubleNotUsed: '2x: Δεν χρησιμοποιήθηκε',
    categoryBreakdown: 'Ανάλυση Κατηγοριών',
    playAgain: 'Παίξε Ξανά ⚽',
    // Home
    appTitle: 'Unlimited Quizball',
    appTitlePart1: 'Unlimited',
    appTitlePart2: 'Quizball',
    appSubtitle: 'Το ποδοσφαιρικό κουίζ',
    signOut: 'Αποσύνδεση',
    btn2Player: 'Παιχνίδι 2 Παικτών',
    btn2PlayerResume: 'Συνέχισε 2 Παίκτες',
    btnSolo: 'Solo Ranked',
    btnBlitz: 'Blitz Mode',
    btnDaily: 'Σήμερα στο Ποδόσφαιρο',
    loginRequired: 'Απαιτείται σύνδεση',
    soloStatsHint: 'ELO',
    blitzStatsHint: 'Καλύτερο',
    rankLabel: 'Κατάταξη',
    btn2PlayerHint: '2 παίκτες · 8 κατηγορίες · 1 βοήθεια ο καθένας',
    btnSoloDesc: 'ELO κατάταξη · προσαρμοστική δυσκολία',
    btnBlitzDesc: '60 δευτ. · πολλαπλή επιλογή',
    dailyResetsIn: 'Ανανέωση σε',
    dailyQuestionsLabel: 'ερωτήσεις',
    gameModes: 'Τρόποι Παιχνιδιού',
    viewAll: 'Όλα',
    startMatch: 'Έναρξη Αγώνα',
    localMultiplayer: 'Τοπικό Πολύπαικτο',
    eloSystem: 'ELO ΣΥΣΤΗΜΑ',
    playersOnline: '12K Παίκτες Online',
    speedrun: 'SPEEDRUN',
    dailyPlay: 'Παίξε',
    dailyChallenge: 'Καθημερινή Δοκιμασία',
    // Nav
    navHome: 'Αρχική',
    navInvite: 'Πρόσκληση',
    navLeaderboard: 'Κατάταξη',
    navRank: 'Κατάταξη',
    navProfile: 'Προφίλ',
    // Daily
    dailyTitle: 'Σήμερα στο Ποδόσφαιρο',
    dailySubtitle: 'Σ αυτή τη μέρα στην ιστορία του ποδοσφαίρου.',
    dailySameQuestions: 'Ίδιες ερωτήσεις για όλους σήμερα. Πόσες μπορείς να απαντήσεις;',
    dailyStart: 'Έναρξη Κουίζ',
    dailyLoading: 'Φόρτωση...',
    dailyAllDone: 'Τέλος!',
    dailyQuestionOf: 'Ερώτηση',
    dailyCorrectPct: 'σωστά',
    dailyNoQuestions: 'Δεν υπάρχουν ερωτήσεις για σήμερα. Δοκίμασε αργότερα.',
    dailyLoadFailed: 'Αποτυχία φόρτωσης ερωτήσεων',
    dailyBackBtn: '← Αρχική',
    tapToContinue: 'Πάτα για συνέχεια',
    // Blitz
    blitzTitle: 'Blitz Mode',
    blitzSubtitle: '60 δευτερόλεπτα. Απάντησε όσες περισσότερες μπορείς.',
    blitzBullet1: 'Επίλεξε από 3 επιλογές — χωρίς πληκτρολόγιο',
    blitzBullet2: 'Γρήγορο ρυθμό: κάθε ερώτηση εμφανίζεται αμέσως μετά την απάντηση',
    blitzBullet3: 'Το καλύτερο σκορ σου αποθηκεύεται και κατατάσσεται',
    blitzBullet4: 'Ιδανικό για γρήγορες συνεδρίες και δοκιμή γνώσεων',
    blitzStart: 'Έναρξη Blitz',
    blitzAnswered: 'απαντήσεις',
    blitzTimesUp: 'Τέλος χρόνου!',
    blitzCorrectOutOf: 'σωστά από',
    blitzBackBtn: '← Αρχική',
    // Leaderboard
    lbTitle: 'Κατάταξη',
    lbRefresh: 'Ανανέωση',
    lbLoading: 'Φόρτωση...',
    lbSolo: 'Solo Ranked',
    lbBlitz: 'Blitz Mode',
    lbYou: '(εσύ)',
    lbNoPlayers: 'Δεν υπάρχουν παίκτες ακόμα. Γίνε ο πρώτος!',
    lbNoBlitz: 'Δεν υπάρχουν σκορ Blitz ακόμα. Παίξε τώρα!',
    lbYourRank: 'Η κατάταξή σου',
    lbQuestions: 'ερωτήσεις',
    lbAnswered: 'απαντήσεις',
    lbBest: 'Καλύτερο',
    lbAccuracy: 'ακρίβεια',
    lbLoadFailed: 'Αποτυχία φόρτωσης κατάταξης',
    blitzSessionFailed: 'Αποτυχία εκκίνησης συνεδρίας',
    // Invite
    inviteTitle: 'Πρόσκληση Φίλου',
    inviteSubtitle: 'Μοιράσου τον σύνδεσμο για να δοκιμάσουν το ποδοσφαιρικό κουίζ.',
    inviteCopy: 'Αντιγραφή συνδέσμου',
    inviteCopied: 'Αντιγράφηκε!',
    inviteShare: 'Κοινή χρήση...',
    inviteHowItWorks: 'Πώς λειτουργεί',
    inviteStep1: 'Μοιράσου τον σύνδεσμο με έναν φίλο',
    inviteStep2: 'Θα ανοίξει την εφαρμογή και θα τη δοκιμάσει',
    inviteStep3: 'Παίξτε 2 παίκτες head-to-head στην ίδια συσκευή',
    // Profile
    profileTitle: 'Το Προφίλ σου',
    profileGuestText: 'Συνδέσου για να παρακολουθείς το ELO, τα Blitz σκορ και να ανταγωνιστείς στην κατάταξη.',
    profileSignIn: 'Σύνδεση',
    profileLoading: 'Φόρτωση προφίλ...',
    profileElo: 'ELO',
    profileMaxElo: 'Max ELO',
    profileBlitzBest: 'Blitz Best',
    profileGames: 'Παιχνίδια',
    profileAccuracy: 'Ακρίβεια',
    profilePeakRating: 'Κορυφαία βαθμολογία',
    profileSoloPlayed: 'Solo παιγμένα',
    profileSoloQuestions: 'ερωτήσεις Solo',
    profileViewLeaderboard: 'Προβολή Κατάταξης',
    profileBackToLeaderboard: 'Πίσω στην Κατάταξη',
    // Donate modal
    donateModalTitle: 'Σου αρέσει το παιχνίδι;',
    donateModalMessage: 'Αν το απολαμβάνεις, σκέψου να υποστηρίξεις τον δημιουργό με έναν καφέ. Κάθε βοήθεια μετράει!',
    donateModalSupport: 'Υποστήριξε στο Ko-fi',
    donateModalMaybeLater: 'Ίσως αργότερα',
    navBuyMeACoffee: 'Καφέ για μένα',
  },
} as const;

type TranslationKeys = keyof typeof TRANSLATIONS.en;

const LANG_KEY = 'quizball_lang';

@Injectable({ providedIn: 'root' })
export class LanguageService {
  readonly lang = signal<Language>((localStorage.getItem(LANG_KEY) as Language) ?? 'en');

  readonly t = computed(() => TRANSLATIONS[this.lang()]);

  setLanguage(lang: Language): void {
    this.lang.set(lang);
    localStorage.setItem(LANG_KEY, lang);
  }

  toggle(): void {
    this.setLanguage(this.lang() === 'en' ? 'el' : 'en');
  }
}
